version: '3'
services: 
    service:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        env_file: ./.env_example
        ports: 
            - ${PORT}:${PORT}
        volumes:
            - /usr/app/node_modules
            - ./server:/usr/app
        command: ["npm", "run", "test"]