version: '3'
services: 
    db:
        container_name: db
        image: mysql
        ports:
            - ${DBPORT}:${DBPORT}
        environment: 
            - MYSQL_DATABASE=${DBDATABASE}
            - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
    redis:
        image: redis
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
    nginx:
        restart: always
        build:
            context: ./nginx
        ports: 
            - '3000:80'
        environment: 
            - PORT=${PORT}
        depends_on: 
            - service
    service:
        build: ./server
        restart: always
        env_file: ./.env
        ports: 
            - ${PORT}:${PORT}
        depends_on: 
            - db
            - redis
    client:
        build: ./client
