version: '3'
services: 
    db:
        container_name: db
        image: mysql
        ports:
            - ${DBPORT}:${DBPORT}
        environment: 
            - MYSQL_DATABASE=${DBDATABASE}
            - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
            # > docker exec -it db mysql -uroot -p
    redis:
        image: redis
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3000:80'
        environment: 
            - PORT=${PORT}
        depends_on: 
            - service
    # client:
    #     build:
    #         context: ./client
    #         dockerfile: Dockerfile.dev
    #     volumes:
    #         - /usr/app/node_modules
    #         - ./client:/usr/app
    service:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        restart: always
        env_file: ./.env
        ports: 
            - ${PORT}:${PORT}
        volumes:
            - /usr/app/node_modules
            - ./server:/usr/app
        depends_on: 
            - db
            - redis